//
//  FoodResponseData.swift
//  DAIHY-ORDER
//
//  Created by Pham Khanh Huy on 23/09/2024.
//

import UIKit

extension FoodResponse {
    
    static func getDummyData() -> FoodResponse?{
        if let jsonData = jsonString.data(using: .utf8) {
            do {
                // Decode the JSON into a User instance
                let data = try JSONDecoder().decode(FoodResponse.self, from: jsonData)
                return nil
            } catch {
                
                dLog("Lỗi parse dữ liệu Food")
                return nil
            }
        }
        
        return nil
        
    }
    
    static var jsonString = """
          {
                  "limit": 50,
                  "total_record": 7,
                  "list": [
                      {
                          "id": 41820,
                          "restaurant_id": 2378,
                          "restaurant_brand_id": 3240,
                          "branch_id": -1,
                          "restaurant_kitchen_place_id": 10973,
                          "restaurant_vat_config_id": 113860,
                          "category_id": 4153,
                          "category_name": "Món Ăn",
                          "category_type": 1,
                          "vat_percent": 8.0,
                          "avatar": "/public/resource/avatar_default/default.jpg",
                          "avatar_thump": "",
                          "code": "F0",
                          "prefix": "FOOD0",
                          "name": "Food0",
                          "normalize_name": "F",
                          "description": "0",
                          "original_price": 12999.0,
                          "price": 12999.0,
                          "point_to_purchase": 0,
                          "unit_type": "Bao",
                          "is_addition": 0,
                          "is_addition_like_food": 0,
                          "time_to_completed": 0,
                          "is_special_claim_point": 0,
                          "is_sell_by_weight": 0,
                          "is_allow_review": 0,
                          "is_allow_print": 1,
                          "is_allow_print_fishbowl": 0,
                          "is_allow_purchase_by_point": 0,
                          "is_take_away": 0,
                          "is_best_seller": 0,
                          "is_combo": 0,
                          "is_goods": 0,
                          "is_allow_employee_gift": 0,
                          "sale_online_status": 0,
                          "status": 1,
                          "is_deleted": 0,
                          "temporary_percent": 0,
                          "temporary_price_from_date": "",
                          "temporary_price_to_date": "",
                          "temporary_price": 0.0,
                          "is_allow_booking": 0,
                          "is_allow_completed_and_approved_for_drink": 0,
                          "is_allow_print_stamp": 0,
                          "price_with_temporary": 12999.0,
                          "is_out_stock": 0,
                          "food_addition_ids": [],
                          "combo_food_ids": [],
                          "addition_foods": [],
                          "food_in_combo": [],
                          "food_list_in_promotion_buy_one_get_one": [],
                          "block_price": 0.0,
                          "time_per_block": 0,
                          "time_block_price": 0,
                          "is_enable_block": 0,
                          "minimum_block_price": 0.0,
                          "is_disable_sell": 0
                      },
                      {
                          "id": 43514,
                          "restaurant_id": 2378,
                          "restaurant_brand_id": 3240,
                          "branch_id": -1,
                          "restaurant_kitchen_place_id": 10973,
                          "restaurant_vat_config_id": 0,
                          "category_id": 4153,
                          "category_name": "Món Ăn",
                          "category_type": 1,
                          "vat_percent": 0.0,
                          "avatar": "qearQ1fWEE2cLDfZ6lB_F",
                          "avatar_thump": "",
                          "code": "MY43513",
                          "prefix": "MI Y",
                          "name": "Mì ý",
                          "normalize_name": "MÝ",
                          "description": "0",
                          "original_price": 80000.0,
                          "price": 80000.0,
                          "point_to_purchase": 0,
                          "unit_type": "Bao",
                          "is_addition": 0,
                          "is_addition_like_food": 0,
                          "time_to_completed": 0,
                          "is_special_claim_point": 0,
                          "is_sell_by_weight": 0,
                          "is_allow_review": 0,
                          "is_allow_print": 1,
                          "is_allow_print_fishbowl": 0,
                          "is_allow_purchase_by_point": 0,
                          "is_take_away": 0,
                          "is_best_seller": 0,
                          "is_combo": 0,
                          "is_goods": 0,
                          "is_allow_employee_gift": 0,
                          "sale_online_status": 0,
                          "status": 1,
                          "is_deleted": 0,
                          "temporary_percent": 0,
                          "temporary_price_from_date": "2024-05-09 10:25:00",
                          "temporary_price_to_date": "2024-05-16 22:21:00",
                          "temporary_price": 0.0,
                          "is_allow_booking": 0,
                          "is_allow_completed_and_approved_for_drink": 0,
                          "is_allow_print_stamp": 1,
                          "price_with_temporary": 80000.0,
                          "is_out_stock": 0,
                          "food_addition_ids": [
                              43462,
                              43461
                          ],
                          "combo_food_ids": [],
                          "addition_foods": [
                              {
                                  "id": 43461,
                                  "name": "topping 1",
                                  "price": 12000.0,
                                  "avatar": "4i4eXF3Vcwf0Kd65duotC",
                                  "unit_type": "Bao",
                                  "vat_percent": 0,
                                  "is_out_stock": 0,
                                  "temporary_price": 0,
                                  "price_with_temporary": 12000.0
                              },
                              {
                                  "id": 43462,
                                  "name": "toping 2",
                                  "price": 20000.0,
                                  "avatar": "/public/resource/avatar_default/default.jpg",
                                  "unit_type": "Bao",
                                  "vat_percent": 0,
                                  "is_out_stock": 0,
                                  "temporary_price": 0,
                                  "price_with_temporary": 20000.0
                              }
                          ],
                          "food_in_combo": [],
                          "food_list_in_promotion_buy_one_get_one": [],
                          "block_price": 0.0,
                          "time_per_block": 0,
                          "time_block_price": 0,
                          "is_enable_block": 0,
                          "minimum_block_price": 0.0,
                          "is_disable_sell": 0
                      },
                      {
                          "id": 43464,
                          "restaurant_id": 2378,
                          "restaurant_brand_id": 3240,
                          "branch_id": -1,
                          "restaurant_kitchen_place_id": 10974,
                          "restaurant_vat_config_id": 0,
                          "category_id": 4154,
                          "category_name": "Đồ uống",
                          "category_type": 2,
                          "vat_percent": 0.0,
                          "avatar": "/public/resource/avatar_default/default.jpg",
                          "avatar_thump": "",
                          "code": "C43463",
                          "prefix": "CAM",
                          "name": "cam",
                          "normalize_name": "C",
                          "description": "0",
                          "original_price": 35000.0,
                          "price": 35000.0,
                          "point_to_purchase": 0,
                          "unit_type": "Bao",
                          "is_addition": 0,
                          "is_addition_like_food": 0,
                          "time_to_completed": 0,
                          "is_special_claim_point": 0,
                          "is_sell_by_weight": 0,
                          "is_allow_review": 0,
                          "is_allow_print": 1,
                          "is_allow_print_fishbowl": 0,
                          "is_allow_purchase_by_point": 0,
                          "is_take_away": 0,
                          "is_best_seller": 0,
                          "is_combo": 0,
                          "is_goods": 0,
                          "is_allow_employee_gift": 0,
                          "sale_online_status": 0,
                          "status": 1,
                          "is_deleted": 0,
                          "temporary_percent": 0,
                          "temporary_price_from_date": "",
                          "temporary_price_to_date": "",
                          "temporary_price": 0.0,
                          "is_allow_booking": 0,
                          "is_allow_completed_and_approved_for_drink": 0,
                          "is_allow_print_stamp": 1,
                          "price_with_temporary": 35000.0,
                          "is_out_stock": 0,
                          "food_addition_ids": [],
                          "combo_food_ids": [],
                          "addition_foods": [],
                          "food_in_combo": [],
                          "food_list_in_promotion_buy_one_get_one": [],
                          "block_price": 0.0,
                          "time_per_block": 0,
                          "time_block_price": 0,
                          "is_enable_block": 0,
                          "minimum_block_price": 0.0,
                          "is_disable_sell": 0
                      },
                      {
                          "id": 43463,
                          "restaurant_id": 2378,
                          "restaurant_brand_id": 3240,
                          "branch_id": -1,
                          "restaurant_kitchen_place_id": 10973,
                          "restaurant_vat_config_id": 0,
                          "category_id": 4153,
                          "category_name": "Món Ăn",
                          "category_type": 1,
                          "vat_percent": 0.0,
                          "avatar": "/public/resource/avatar_default/default.jpg",
                          "avatar_thump": "",
                          "code": "F343462",
                          "prefix": "FOOD 3",
                          "name": "food 3",
                          "normalize_name": "F3",
                          "description": "0",
                          "original_price": 250000.0,
                          "price": 250000.0,
                          "point_to_purchase": 0,
                          "unit_type": "Bao",
                          "is_addition": 0,
                          "is_addition_like_food": 0,
                          "time_to_completed": 0,
                          "is_special_claim_point": 0,
                          "is_sell_by_weight": 0,
                          "is_allow_review": 0,
                          "is_allow_print": 1,
                          "is_allow_print_fishbowl": 0,
                          "is_allow_purchase_by_point": 0,
                          "is_take_away": 0,
                          "is_best_seller": 0,
                          "is_combo": 0,
                          "is_goods": 0,
                          "is_allow_employee_gift": 0,
                          "sale_online_status": 0,
                          "status": 1,
                          "is_deleted": 0,
                          "temporary_percent": 0,
                          "temporary_price_from_date": "",
                          "temporary_price_to_date": "",
                          "temporary_price": 0.0,
                          "is_allow_booking": 0,
                          "is_allow_completed_and_approved_for_drink": 0,
                          "is_allow_print_stamp": 1,
                          "price_with_temporary": 250000.0,
                          "is_out_stock": 0,
                          "food_addition_ids": [
                              43462,
                              43461
                          ],
                          "combo_food_ids": [],
                          "addition_foods": [
                              {
                                  "id": 43461,
                                  "name": "topping 1",
                                  "price": 12000.0,
                                  "avatar": "4i4eXF3Vcwf0Kd65duotC",
                                  "unit_type": "Bao",
                                  "vat_percent": 0,
                                  "is_out_stock": 0,
                                  "temporary_price": 0,
                                  "price_with_temporary": 12000.0
                              },
                              {
                                  "id": 43462,
                                  "name": "toping 2",
                                  "price": 20000.0,
                                  "avatar": "/public/resource/avatar_default/default.jpg",
                                  "unit_type": "Bao",
                                  "vat_percent": 0,
                                  "is_out_stock": 0,
                                  "temporary_price": 0,
                                  "price_with_temporary": 20000.0
                              }
                          ],
                          "food_in_combo": [],
                          "food_list_in_promotion_buy_one_get_one": [],
                          "block_price": 0.0,
                          "time_per_block": 0,
                          "time_block_price": 0,
                          "is_enable_block": 0,
                          "minimum_block_price": 0.0,
                          "is_disable_sell": 0
                      },
                      {
                          "id": 43513,
                          "restaurant_id": 2378,
                          "restaurant_brand_id": 3240,
                          "branch_id": -1,
                          "restaurant_kitchen_place_id": 10973,
                          "restaurant_vat_config_id": 0,
                          "category_id": 4153,
                          "category_name": "Món Ăn",
                          "category_type": 1,
                          "vat_percent": 0.0,
                          "avatar": "I5dE8KEkbnjVi03PzItuL",
                          "avatar_thump": "",
                          "code": "GR43464",
                          "prefix": "GA RAN",
                          "name": "gà rán",
                          "normalize_name": "GR",
                          "description": "0",
                          "original_price": 50000.0,
                          "price": 50000.0,
                          "point_to_purchase": 0,
                          "unit_type": "Bao",
                          "is_addition": 0,
                          "is_addition_like_food": 0,
                          "time_to_completed": 0,
                          "is_special_claim_point": 0,
                          "is_sell_by_weight": 0,
                          "is_allow_review": 0,
                          "is_allow_print": 1,
                          "is_allow_print_fishbowl": 0,
                          "is_allow_purchase_by_point": 0,
                          "is_take_away": 0,
                          "is_best_seller": 0,
                          "is_combo": 0,
                          "is_goods": 0,
                          "is_allow_employee_gift": 0,
                          "sale_online_status": 0,
                          "status": 1,
                          "is_deleted": 0,
                          "temporary_percent": 0,
                          "temporary_price_from_date": "2024-05-09 10:25:00",
                          "temporary_price_to_date": "2024-05-13 10:20:00",
                          "temporary_price": 0.0,
                          "is_allow_booking": 0,
                          "is_allow_completed_and_approved_for_drink": 0,
                          "is_allow_print_stamp": 1,
                          "price_with_temporary": 50000.0,
                          "is_out_stock": 0,
                          "food_addition_ids": [
                              43462,
                              43461
                          ],
                          "combo_food_ids": [],
                          "addition_foods": [
                              {
                                  "id": 43461,
                                  "name": "topping 1",
                                  "price": 12000.0,
                                  "avatar": "4i4eXF3Vcwf0Kd65duotC",
                                  "unit_type": "Bao",
                                  "vat_percent": 0,
                                  "is_out_stock": 0,
                                  "temporary_price": 0,
                                  "price_with_temporary": 12000.0
                              },
                              {
                                  "id": 43462,
                                  "name": "toping 2",
                                  "price": 20000.0,
                                  "avatar": "/public/resource/avatar_default/default.jpg",
                                  "unit_type": "Bao",
                                  "vat_percent": 0,
                                  "is_out_stock": 0,
                                  "temporary_price": 0,
                                  "price_with_temporary": 20000.0
                              }
                          ],
                          "food_in_combo": [],
                          "food_list_in_promotion_buy_one_get_one": [],
                          "block_price": 0.0,
                          "time_per_block": 0,
                          "time_block_price": 0,
                          "is_enable_block": 0,
                          "minimum_block_price": 0.0,
                          "is_disable_sell": 0
                      },
                      {
                          "id": 46614,
                          "restaurant_id": 2378,
                          "restaurant_brand_id": 3240,
                          "branch_id": -1,
                          "restaurant_kitchen_place_id": 10974,
                          "restaurant_vat_config_id": 0,
                          "category_id": 4154,
                          "category_name": "Đồ uống",
                          "category_type": 2,
                          "vat_percent": 0.0,
                          "avatar": "",
                          "avatar_thump": "",
                          "code": "HUYTESTMONNUOC43514",
                          "prefix": "HTMN",
                          "name": "huy test món nước",
                          "normalize_name": "huy test mon nuoc",
                          "description": "0",
                          "original_price": 100000.0,
                          "price": 100000.0,
                          "point_to_purchase": 0,
                          "unit_type": "Bao",
                          "is_addition": 0,
                          "is_addition_like_food": 0,
                          "time_to_completed": 0,
                          "is_special_claim_point": 0,
                          "is_sell_by_weight": 0,
                          "is_allow_review": 0,
                          "is_allow_print": 1,
                          "is_allow_print_fishbowl": 0,
                          "is_allow_purchase_by_point": 0,
                          "is_take_away": 0,
                          "is_best_seller": 0,
                          "is_combo": 0,
                          "is_goods": 0,
                          "is_allow_employee_gift": 0,
                          "sale_online_status": 0,
                          "status": 1,
                          "is_deleted": 0,
                          "temporary_percent": 0,
                          "temporary_price_from_date": "",
                          "temporary_price_to_date": "",
                          "temporary_price": 0.0,
                          "is_allow_booking": 0,
                          "is_allow_completed_and_approved_for_drink": 0,
                          "is_allow_print_stamp": 1,
                          "price_with_temporary": 100000.0,
                          "is_out_stock": 0,
                          "food_addition_ids": [],
                          "combo_food_ids": [],
                          "addition_foods": [],
                          "food_in_combo": [],
                          "food_list_in_promotion_buy_one_get_one": [],
                          "block_price": 0.0,
                          "time_per_block": 0,
                          "time_block_price": 0,
                          "is_enable_block": 0,
                          "minimum_block_price": 0.0,
                          "is_disable_sell": 0
                      },
                      {
                          "id": 43461,
                          "restaurant_id": 2378,
                          "restaurant_brand_id": 3240,
                          "branch_id": -1,
                          "restaurant_kitchen_place_id": 10973,
                          "restaurant_vat_config_id": 0,
                          "category_id": 4153,
                          "category_name": "Món Ăn",
                          "category_type": 1,
                          "vat_percent": 0.0,
                          "avatar": "4i4eXF3Vcwf0Kd65duotC",
                          "avatar_thump": "4i4eXF3Vcwf0Kd65duotC",
                          "code": "T141821",
                          "prefix": "TOPPING 1",
                          "name": "topping 1",
                          "normalize_name": "T1",
                          "description": "0",
                          "original_price": 12000.0,
                          "price": 12000.0,
                          "point_to_purchase": 0,
                          "unit_type": "Bao",
                          "is_addition": 1,
                          "is_addition_like_food": 1,
                          "time_to_completed": 0,
                          "is_special_claim_point": 0,
                          "is_sell_by_weight": 0,
                          "is_allow_review": 0,
                          "is_allow_print": 1,
                          "is_allow_print_fishbowl": 0,
                          "is_allow_purchase_by_point": 0,
                          "is_take_away": 0,
                          "is_best_seller": 0,
                          "is_combo": 0,
                          "is_goods": 0,
                          "is_allow_employee_gift": 0,
                          "sale_online_status": 0,
                          "status": 1,
                          "is_deleted": 0,
                          "temporary_percent": 0,
                          "temporary_price_from_date": "2024-05-07 11:15:00",
                          "temporary_price_to_date": "2024-05-25 11:12:00",
                          "temporary_price": 0.0,
                          "is_allow_booking": 0,
                          "is_allow_completed_and_approved_for_drink": 0,
                          "is_allow_print_stamp": 0,
                          "price_with_temporary": 12000.0,
                          "is_out_stock": 0,
                          "food_addition_ids": [],
                          "combo_food_ids": [],
                          "addition_foods": [],
                          "food_in_combo": [],
                          "food_list_in_promotion_buy_one_get_one": [],
                          "block_price": 0.0,
                          "time_per_block": 0,
                          "time_block_price": 0,
                          "is_enable_block": 0,
                          "minimum_block_price": 0.0,
                          "is_disable_sell": 0
                      }
                  ]
              }
        """
}
